### ISSUE TITLE
[Plan] - Review Environment

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-dynamic-planning#87]
This is a comment related to the page [Plan](//w3c.github.io/wai-dynamic-planning/plan/index.html)

We talk about authoring tools supporting accessibility and staff skills, but don't mention access to checking tools for authors/developers. Not urgent, but for consideration as part of the working environment, e.g.

"Do your staff have access to an appropriate toolkit for testing accessibility?"

**Comment by nitedog** [comment]
I agree with adding in the suggested question. However, I mildly dislike adding the tools list to "review environment" section, as most of these tools are focused on evaluating content rather than the aspects addressed in this section. Re-opening for editor's discretion but feel free to close if you disagree. Maybe reference "selecting evaluation tools" rather than the "tools list" itself?

**Comment by iadawn** [comment]
I think in this case there is value in linking to the list of tools. The added question relates to whether suitable tools are available to assist in the evaluation process. The list then points them to tools that would fulfil this need.

The link to 'Selecting evaluation tools' already exists as more information to this item. The might benefit from a little reordering though.

**Comment by nitedog** [comment]
I think the term "tools" here is intended more broadly, like authoring tools, quality management tools, and customer feedback mechanisms?

**Comment by iadawn** [comment]
The whole section talks about a variety of tools as you suggest. However, the added consideration calls out tools used to assist testing specifically. That is why I felt the list of evaluation tools would be of potential benefit.
